// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ODPC.Data;

#nullable disable

namespace ODPC.Migrations
{
    [DbContext(typeof(OdpcDbContext))]
    [Migration("20240925095407_GroepenDynamisch")]
    partial class GroepenDynamisch
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ODPC.Data.Entities.Gebruikersgroep", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Omschrijving")
                        .HasColumnType("text");

                    b.HasKey("Uuid");

                    b.ToTable("Gebruikersgroepen");

                    b.HasData(
                        new
                        {
                            Uuid = new Guid("d3da5277-ea07-4921-97b8-e9a181390c76"),
                            Naam = "Groep 1"
                        },
                        new
                        {
                            Uuid = new Guid("8f939b51-dad3-436d-a5fa-495b42317d64"),
                            Naam = "Groep 2"
                        },
                        new
                        {
                            Uuid = new Guid("0e7a0023-423a-421a-8700-359232fef584"),
                            Naam = "Groep 3"
                        });
                });

            modelBuilder.Entity("ODPC.Data.Entities.GebruikersgroepWaardelijst", b =>
                {
                    b.Property<Guid>("GebruikersgroepUuid")
                        .HasColumnType("uuid");

                    b.Property<string>("WaardelijstId")
                        .HasColumnType("text");

                    b.HasKey("GebruikersgroepUuid", "WaardelijstId");

                    b.ToTable("GebruikersgroepWaardelijsten");
                });

            modelBuilder.Entity("ODPC.Data.Entities.GebruikersgroepWaardelijst", b =>
                {
                    b.HasOne("ODPC.Data.Entities.Gebruikersgroep", "Gebruikersgroep")
                        .WithMany()
                        .HasForeignKey("GebruikersgroepUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gebruikersgroep");
                });
#pragma warning restore 612, 618
        }
    }
}
