// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ODPC.Data;

#nullable disable

namespace ODPC.Migrations
{
    [DbContext(typeof(OdpcDbContext))]
    [Migration("20240923160219_Auditregels")]
    partial class Auditregels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ODPC.Data.Entities.Auditregel", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Aanmaakdatum")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("Actie")
                        .HasColumnType("integer");

                    b.Property<string>("ActieWeergave")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GebruikersId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Geslaagd")
                        .HasColumnType("boolean");

                    b.Property<string>("Resource")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ResourceUuid")
                        .HasColumnType("uuid");

                    b.Property<string>("ResourceWeergave")
                        .HasColumnType("text");

                    b.Property<int>("Resultaat")
                        .HasColumnType("integer");

                    b.Property<string>("ResultaatWeergave")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Uuid");

                    b.HasIndex("GebruikersId");

                    b.HasIndex("Geslaagd");

                    b.HasIndex("Resource");

                    b.HasIndex("ResourceUuid");

                    b.ToTable("Auditregels");
                });

            modelBuilder.Entity("ODPC.Data.Entities.Gebruikersgroep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Gebruikersgroepen");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d3da5277-ea07-4921-97b8-e9a181390c76"),
                            Name = "Groep 1"
                        },
                        new
                        {
                            Id = new Guid("8f939b51-dad3-436d-a5fa-495b42317d64"),
                            Name = "Groep 2"
                        },
                        new
                        {
                            Id = new Guid("0e7a0023-423a-421a-8700-359232fef584"),
                            Name = "Groep 3"
                        });
                });

            modelBuilder.Entity("ODPC.Data.Entities.GebruikersgroepWaardelijst", b =>
                {
                    b.Property<Guid>("GebruikersgroepId")
                        .HasColumnType("uuid");

                    b.Property<string>("WaardelijstId")
                        .HasColumnType("text");

                    b.HasKey("GebruikersgroepId", "WaardelijstId");

                    b.ToTable("GebruikersgroepWaardelijsten");
                });

            modelBuilder.Entity("ODPC.Data.Entities.Auditregel", b =>
                {
                    b.OwnsOne("ODPC.Data.Entities.AuditregelWijziging", "Wijzigingen", b1 =>
                        {
                            b1.Property<Guid>("AuditregelUuid")
                                .HasColumnType("uuid");

                            b1.Property<byte[]>("Nieuw")
                                .HasColumnType("bytea");

                            b1.Property<byte[]>("Oud")
                                .HasColumnType("bytea");

                            b1.HasKey("AuditregelUuid");

                            b1.ToTable("Auditregels");

                            b1.WithOwner()
                                .HasForeignKey("AuditregelUuid");
                        });

                    b.Navigation("Wijzigingen")
                        .IsRequired();
                });

            modelBuilder.Entity("ODPC.Data.Entities.GebruikersgroepWaardelijst", b =>
                {
                    b.HasOne("ODPC.Data.Entities.Gebruikersgroep", "Gebruikersgroep")
                        .WithMany()
                        .HasForeignKey("GebruikersgroepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gebruikersgroep");
                });
#pragma warning restore 612, 618
        }
    }
}
