// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ODPC.Data;

#nullable disable

namespace ODPC.Migrations
{
    [DbContext(typeof(OdpcDbContext))]
    [Migration("20240829134731_AddWeatherForecastTable")]
    partial class AddWeatherForecastTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ODPC.WeatherForecast", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Summary")
                        .HasColumnType("text");

                    b.Property<int>("TemperatureC")
                        .HasColumnType("integer");

                    b.HasKey("Guid");

                    b.ToTable("WeatherForecasts");

                    b.HasData(
                        new
                        {
                            Guid = new Guid("e31771d6-c6c4-4ff8-a2da-72b90847ac27"),
                            Date = new DateOnly(2024, 8, 30),
                            Summary = "Mild",
                            TemperatureC = 20
                        },
                        new
                        {
                            Guid = new Guid("4fa89832-2627-412e-b749-4b4da3ee0f93"),
                            Date = new DateOnly(2024, 8, 31),
                            Summary = "Warm",
                            TemperatureC = 25
                        },
                        new
                        {
                            Guid = new Guid("66a7c17a-2822-4dd1-b9cd-b18d6ebc4bb9"),
                            Date = new DateOnly(2024, 9, 1),
                            Summary = "Cool",
                            TemperatureC = 15
                        },
                        new
                        {
                            Guid = new Guid("cc957f44-67fb-43ee-9eb9-8a263fd80375"),
                            Date = new DateOnly(2024, 9, 2),
                            Summary = "Hot",
                            TemperatureC = 30
                        },
                        new
                        {
                            Guid = new Guid("535309b4-d6ef-42eb-8306-9ab834b795d8"),
                            Date = new DateOnly(2024, 9, 3),
                            Summary = "Chilly",
                            TemperatureC = 10
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
